### ISSUE TITLE
which fix for using that init.rc or someone of galaxy nexus? 

### ISSUE THREAD

**Issue by kkangs** [kensuke/How-to-Miracast-on-AOSP#5]
Galaxy nexus last version that 4.3 jellybean

So from the wifi, you were some fix that for using 4.4kikat on galaxy nexus

How to fix them? Where some fix? Thank reply

**Comment by kensuke** [comment]
GN's stock ROM has wifi problem?

**Comment by kkangs** [comment]
Modified Files
base src: AOSP 4.4_r1
driver files: merge 4.3
/device/samsung/*: merge AOSP 4.3_r2.2
/device/samsung/tuna/init.tuna.rc: tiny fix for Wi-Fi
/device/samsung/tuna/libsensors: tiny fix for build error
<several Miracast Patches> -> See https://github.com/kensuke/How-to-Miracast-on-AOSP/wiki
/external/wpa_supplicant_8/wpa_supplicant/p2p_supplicant.c: P2p Capability Check Skipped!! I read a xda forum thread. 
Wrote it. 

Modified Files
base src: AOSP 4.4_r1
driver files: merge 4.3
/device/samsung/*: merge AOSP 4.3_r2.2
/device/samsung/tuna/init.tuna.rc: tiny fix for Wi-Fi
/device/samsung/tuna/libsensors: tiny fix for build error
<several Miracast Patches> -> See https://github.com/kensuke/How-to-Miracast-on-AOSP/wiki
/external/wpa_supplicant_8/wpa_supplicant/p2p_supplicant.c: P2p Capability Check Skipped!!

**Comment by kkangs** [comment]
I read init.tuna.rc and libsensors tiny error fix. What is some error and tiny fix this? I will 4.4 merged from 4.3 of GN.

**Comment by kensuke** [comment]
it's only avoiding compile error.
I already posted differential source code from 4.3 and 4.4 to xda thread. (maybe maguro custom rom "Dreams" thread)
I'll go home, search zip archive on my pc.

**Comment by kkangs** [comment]
Aha it is using custom rom on the running 4.4? Ok i will waiting for archive :)

**Comment by kensuke** [comment]
http://forum.xda-developers.com/showpost.php?p=52562917&postcount=56

**Comment by kkangs** [comment]
thank you for ur advise. but i have one error.
i'm running on galaxy nexus on 4.4.4 (KTU84P) working some.
but in the logcat, could not open keymaster device error and in the Unique_ptr.h, algorithm STL include error. so some fix and compile ok, continued keymaster error.
Did you have one?

**Comment by kensuke** [comment]
http://www.reddit.com/r/nexus4/comments/18mzix/setting_crashes_after_updating_to_android_422/

**Comment by kkangs** [comment]
thanks. but my Galaxy nexus don't have /vender/firware/keymaster directory.
 i think that it is depenicies for hardware (ap OMAP4xxx)

**Comment by kkangs** [comment]
i solve the problem. using cm11 :)
